### PR TITLE
feat: implement base64 encoding

### PR DESCRIPTION
**Pull request by sno2**

### CODE REVIEW

**Comment by sno2** [comment]
These are mostly primitive implementations for bitwise AND/OR/XOR. Proper handling still needs to be done for negative numbers but I want to work on something with these operators for only unsigned data for the moment. Also, we could do a binary search on the `Pow2` with the `N1`/`N2` to find out the needed power map. It sadly iterates through all of them currently.

**Comment by sno2** [comment]
Is anyone else able to look at my work? For some reason, I'm getting "this type is possibly infinite" errors. However, when you hover over the following type in the IDE, it shows the correct value:

```ts
import { Call, E } from ".";

type A = Call<E.Btoa, "Hello">;
//   ^? "SGVsbG8="
```

**Review by perrystan1489 — APPROVED** [review]

**Comment by sno2** [comment]
Hmm, I think I have an idea to circumvent this, but it's going to be ugly.

**Comment by sno2** [comment]
Regarding the needed optimization for the bitwise operators and finding the correct starting point on the power table. We should be able to implement a fast `Log2` type that uses a precomputed table for the most common powers (e.g. 1-32). I'll work on that tomorrow.

**Comment by gvergnaud** [comment]
You should join the discord: https://discord.gg/kaegdW3z

**Comment by perrystan1489** [comment]
It says I’m at the server limit! Do I need to leave some

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sno2** [comment]
Alright, this is ready for review. I did not add on the `Log2` optimization I was talking about for the bitwise operators yet because I think we should be able to make a `Tuples.BinarySearch` implementation with sorters that would automatically do it for us.

**Review by perrystan1489 — APPROVED** [review]

**Review by perrystan1489 — APPROVED** [review]

**Comment by ecyrbe** [comment]
I'm closing this.
It's an howesome  algorithm achievement, but it's a really narrowed use case that does not fit the purpose of this library in being a collection of building blocks to create higher end algorithms.

**Pull request closed without merging**
