### PR TITLE
feat(functions): add ts function utility types

### PR DESCRIPTION
**Pull request by ecyrbe**
This add some of Functions utility types : 
- IdentityFn : to allow functional composition in the future
- Parameters: extract parameters from a function definition
- Parameter: extract one parameter from a function definition
- Return : rextract return type from a function definition

### CODE REVIEW

**Comment by gvergnaud** [comment]
Awesome, thanks for contributing !

Could you rebase your branch? I created a Functions namespace in a previous commit and this is conflicting with it

**Comment by ecyrbe** [comment]
done!

**Comment by ecyrbe** [comment]
rebased.
if we can merge this would be awesome, rebasing is not fun

**Review by gvergnaud — APPROVED** [review]
awesome

**Pull request merged**
